ref_centers: [
  [-0.76, -0.21],
  [ 0.76, -0.21],
  [-0.76,  0.21],
]
circle_radius: 0.14
max_diagonal: 2.3
circle_radius_thresh: 0.02
grad_thresh: 1.0
min_range: 1.0
max_range: 10.0
range_interpolation_threshold: 0.0
min_plateau_len: 0.05
plane_niter: 100
plane_dist_thresh: 0.1
line_niter: 100
line_dist_thresh: 0.01
min_line_inliers: 15
enforce_circle_radius: True
circle_niter: 100
circle_dist_thresh: 0.02
geom_consist_thresh: 0.06
