- trans_abs: 0.0
  rot_abs_deg: 0.0
  desc: '0.0'

- trans_abs: 0.005
  rot_abs_deg: 0.1
  desc: '1.0'

- trans_abs: 0.010
  rot_abs_deg: 0.2
  desc: '2.0'

- trans_abs: 0.025
  rot_abs_deg: 0.5
  desc: '5.0'

- trans_abs: 0.05
  rot_abs_deg: 1.0
  desc: '10.0'
