name: DualQuaternionQCQP
ransac:
  base: POINT2POINT
  trans_thresh: 0.1
  nreps: 100
  seed: 0
sync: 0.005
#transform_filter:
#  min_translation: 0.0
#  max_translation: 1.0
#  min_rotation_deg: 0.0
#  max_rotation_deg: 5.0
